version: '3.4'

services:

  gitlab-runner:
    image: gitlab/gitlab-runner:v13.3.1
    restart: always
    networks:
      - gitlab-tier
    volumes:
      - /docker/gitlab-runner/config:/etc/gitlab-runner:Z
      - /docker/gitlab-runner/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
    command: register --non-interactive --executor "docker" --url ${URL} --registration-token ${REGISTRATION-TOKEN}

networks:
  gitlab-tier:
    external: true