

# default environment = wekan.env
version: '3'
services:
  # 数据库 mongodb------------------------------------------------------------------------------
  wekandb:
    image: mongo:3.2.20
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    ports:
      - 27017:27017
    volumes:
      - /docker/wekandb/data:/data/db
      - /docker/wekandb/dump:/dump

    # wekan -------------------------------------------------------------------------------------
  wekan:
    image: wekanteam/wekan:v2.17
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 8080:8080
    #---------------------------------------------------------------------------------------------
    environment:
      - MONGO_URL=${MONGO_URL}
      - ROOT_URL=${ROOT_URL}
      - WITH_API=${WITH_API}
      - BROWSER_POLICY_ENABLED=${BROWSER_POLICY_ENABLED}
    depends_on:
      - wekandb
networks:
  wekan-tier:
    driver: bridge