version: '3'

services:

  wekandb:
    #-------------------------------------------------------------------------------------
    image: mongo:4.2
    container_name: wekan-db
    restart: always
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /docker/wekan/wekan-db:/data/db
      - /docker/wekan/wekan-db-dump:/dump
    command: mongod --oplogSize 128

  wekan:
    #-------------------------------------------------------------------------------------
    image: wekanteam/wekan:v4.23
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 10001:8080
    environment:
      - MONGO_URL=${MONGO_URL}
      - ROOT_URL=${ROOT_URL}
      - MAIL_URL=${MAIL_URL}
      - MAIL_FROM=${MAIL_FROM}
      - WITH_API=${WITH_API}
      - RICHER_CARD_COMMENT_EDITOR=${RICHER_CARD_COMMENT_EDITOR}
      - CORS=${CORS}
      - BROWSER_POLICY_ENABLED=${BROWSER_POLICY_ENABLED}
    depends_on:
      - wekandb

networks:
  wekan-tier:
    driver: bridge