version: "3"



services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./data:/var/lib/mysql
      - ./data:/etc/mysql/conf.d
    ports:
      - 13306:3306
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    restart: always
